'use client'

import { Download, FileText } from 'lucide-react'
import type { Message } from '@/lib/kv44-types'
import { cn } from '@/lib/utils'
import { KvLogo } from './kv-logo'
import { Markdown } from './markdown'

function TypingDots() {
  return (
    <div className="flex items-center gap-1.5 py-1">
      {[0, 1, 2].map((i) => (
        <span
          key={i}
          className="kv-typing-dot size-2 rounded-full bg-primary"
          style={{ animationDelay: `${i * 0.18}s` }}
        />
      ))}
    </div>
  )
}

function DownloadButton({ href, name }: { href: string; name: string }) {
  return (
    <a
      href={href}
      download={name}
      className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-card px-3 py-1.5 text-xs font-medium transition-colors hover:border-primary/40 hover:text-primary"
    >
      <Download className="size-3.5" />
      Download
    </a>
  )
}

function UserAttachments({ message }: { message: Message }) {
  if (!message.attachments?.length) return null
  const images = message.attachments.filter((a) => a.kind === 'image')
  const files = message.attachments.filter((a) => a.kind === 'file')

  return (
    <div className="mb-2 flex flex-col gap-2">
      {images.length > 0 && (
        <div className="flex flex-wrap justify-end gap-2">
          {images.map((img, i) => (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              key={i}
              src={img.url || '/placeholder.svg'}
              alt={img.name || `Uploaded image ${i + 1}`}
              className="size-24 rounded-xl border border-primary-foreground/20 object-cover"
            />
          ))}
        </div>
      )}
      {files.map((f, i) => (
        <div
          key={i}
          className="flex items-center gap-2 self-end rounded-xl bg-primary-foreground/15 px-3 py-2 text-sm"
        >
          <FileText className="size-4 shrink-0" />
          <span className="max-w-[200px] truncate">{f.name}</span>
        </div>
      ))}
    </div>
  )
}

function MessageBubble({ message, isStreaming }: { message: Message; isStreaming: boolean }) {
  const isUser = message.role === 'user'

  if (isUser) {
    return (
      <div className="flex flex-col items-end">
        <UserAttachments message={message} />
        {message.content && (
          <div className="max-w-[85%] rounded-2xl rounded-tr-md bg-primary px-4 py-2.5 text-[15px] leading-relaxed text-primary-foreground">
            <p className="whitespace-pre-wrap">{message.content}</p>
          </div>
        )}
      </div>
    )
  }

  return (
    <div className="flex gap-3">
      <KvLogo className="size-8 shrink-0 rounded-xl text-xs" />
      <div className="min-w-0 flex-1 pt-0.5">
        <div
          className={cn(
            'max-w-[95%] rounded-2xl rounded-tl-md border border-border bg-card px-4 py-3',
            message.error && 'border-destructive/40 bg-destructive/5 text-destructive',
          )}
        >
          {message.content ? (
            <Markdown content={message.content} />
          ) : isStreaming ? (
            <TypingDots />
          ) : null}

          {message.generatedImage && (
            <div className="mt-3 space-y-2">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={message.generatedImage || '/placeholder.svg'}
                alt="Generated by Kv-44"
                className="w-full max-w-md rounded-xl border border-border"
              />
              <DownloadButton href={message.generatedImage} name="kv-44-image.png" />
            </div>
          )}

          {message.generatedVideo && (
            <div className="mt-3 space-y-2">
              <video
                src={message.generatedVideo}
                controls
                autoPlay
                loop
                muted
                playsInline
                className="w-full max-w-md rounded-xl border border-border"
              />
              <DownloadButton href={message.generatedVideo} name="kv-44-video.mp4" />
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export function MessageList({
  messages,
  streamingId,
}: {
  messages: Message[]
  streamingId: string | null
}) {
  return (
    <div className="mx-auto flex w-full max-w-3xl flex-col gap-6 px-4 py-6 sm:px-6">
      {messages.map((m) => (
        <div key={m.id} className="kv-fade-up">
          <MessageBubble message={m} isStreaming={streamingId === m.id} />
        </div>
      ))}
    </div>
  )
}
